### ISSUE TITLE
AuraUI brand Logo disappears when the user selects the system theme

### ISSUE THREAD

**Issue by gaurangkeluskar22** [Shubham0850/auraui#13]
**AuraUI brand Logo disappears when the user selects the system theme**

[a522ccaa-a51b-4d90-901a-2aea373761a4.webm](https://github.com/user-attachments/assets/d8164e53-c194-457e-a8a0-541862016e5c)

**Comment by Shubham0850** [comment]
Thanks for creating the issue @gaurangkeluskar22 , If you want to work on this please let me know.

**Comment by gaurangkeluskar22** [comment]
Hi @Shubham0850 , can you please assign this issue to me, would love to contribute.

**Comment by Shubham0850** [comment]
Sorry for the late response @gaurangkeluskar22 , Assigning the task to you.
