### ISSUE TITLE
[BUG] Hero section overflow in animation for a second

### ISSUE THREAD

**Issue by vansh-codes** [Shubham0850/auraui#14]
https://github.com/user-attachments/assets/598ad502-6fcd-45a4-a6cc-b4d262ec998f

As seen in the video, when we go on the settings tab, horizontal scrollbar appears for a second because of the animation css issues
I would love to work on this to fix it!

**Comment by Shubham0850** [comment]
Thanks for creating the issue @vansh-codes , Do you think that you can fix this issue ?

**Comment by vansh-codes** [comment]
Sure @Shubham0850, I would love to!
Do assign me this and I will create a PR
