### ISSUE TITLE
Wrong code in animation/loading

### ISSUE THREAD

**Issue by vansh-codes** [Shubham0850/auraui#15]
https://www.auraui.com/docs/animation/loading

Card's code is pasted in the link given above, whereas there should be loading's code

**Comment by SiddharthaMishra-dev** [comment]
I can help to fix this issue

**Comment by SiddharthaMishra-dev** [comment]
I have noticed that none of the animantion UI is having correct code.
Each one is having code of outer component.
I can update the docs as per 
@Shubham0850

**Comment by Shubham0850** [comment]
Thanks for showing the interest @SiddharthaMishra-dev . 

Here is what i'm thinking to implement. 
1. Remove the Code option from the Loading page.
2. Add copy code button bellow every animation and when user click on the button the code should be copied with some user feedback.
<img width="309" alt="Screenshot 2024-09-01 at 12 05 32 PM" src="https://github.com/user-attachments/assets/acd5a396-3b33-4e0f-8d53-0718c88964e7">

Lemme know if you can do the above mention requirement, then i can assign you the task to you.

**Comment by SiddharthaMishra-dev** [comment]
![image](https://github.com/user-attachments/assets/544ba0fc-9d67-4815-9551-ac76ce590113)

@Shubham0850 . How about this one. I have implemented the copy functionality

**Comment by Shubham0850** [comment]
Looking good @SiddharthaMishra-dev , thanks for working on this.
- Remove border from the copy icon
- align icon and text vertically centre
- make sure the "copy code" button is dark mode compatible

Please let me know if you need any help, feel free to create a PR to discuss other issues if exist.

**Comment by SiddharthaMishra-dev** [comment]
For loading, we have to also remove code panel ..right?
@Shubham0850

**Comment by Shubham0850** [comment]
Looking awesome @SiddharthaMishra-dev , Yes we need to remove the code section in the Loading page.
