### ISSUE TITLE
Missing page docs/loading

### ISSUE THREAD

**Issue by vansh-codes** [Shubham0850/auraui#16]
![image](https://github.com/user-attachments/assets/4252969b-73a4-4c0f-b08e-c6304656559a)

https://www.auraui.com/docs/loading

**Comment by Shubham0850** [comment]
Thanks @vansh-codes for creating the issue. 

Can you please add the steps to reproduce the bug and if you want to solve it then please let me know.

**Comment by vansh-codes** [comment]
Hii @Shubham0850 
It seems to be fixed now!
so I am closing this issue now
