### ISSUE TITLE
docs path not working on navbar

### ISSUE THREAD

**Issue by SiddharthaMishra-dev** [Shubham0850/auraui#27]
**Describe the bug**
On first click on `docs`  in navbar , it is rendering `Components page` . On second click it is rendering `docs` page

**To Reproduce**
It is on the production website 
[AuraUI](https://www.auraui.com/)

**Expected behavior**
It should be rendering `docs` page

**Screenshots**
![Screenshot from 2024-09-03 20-51-57](https://github.com/user-attachments/assets/d454f2e4-8c8d-4d7b-820c-15c8ecc2bfcc)

**Desktop (please complete the following information):**
 - OS: Fedora 40
 - Browser : Firefox, Edge, Chrome

I tried to replicate this issue in development environment but their it is working as expected.
Upon inspection I found href is correctly referring to docs

**Comment by gaurangkeluskar22** [comment]
Hi @Shubham0850, @Jayjeet1013  can you please assign this issue to me, I would love to contribute.

**Comment by Jayjeet1013** [comment]
Hi @gaurangkeluskar22 , sure! I've assigned the issue to you. Looking forward to your contribution!

**Comment by gaurangkeluskar22** [comment]
Hi @Jayjeet1013, I have added PR https://github.com/Shubham0850/auraui/pull/30, please review.

**Comment by ujjwal313** [comment]
Hi @Shubham0850 @Jayjeet1013,
I have made a PR #31.
Can you check and let me know if this fixes your issue?

**Comment by Jayjeet1013** [comment]
Thanks for working on this @ujjwal313 but this solution doesn't work.
