### ISSUE TITLE
Shift the navbar menu to the left, next to the Auraui logo.

### ISSUE THREAD

**Issue by Jayjeet1013** [Shubham0850/auraui#28]
Shift the navbar menu to the left, next to the Auraui logo.

Like this 

Aurui logo,Home,Templates,Docs,Components

**Comment by gaurangkeluskar22** [comment]
Hi @Jayjeet1013, can you please assign this issue to me, I would love to contribute.

**Comment by Jayjeet1013** [comment]
Hi @gaurangkeluskar22 , sure! I've assigned the issue to you. Looking forward to your contribution!

**Comment by gaurangkeluskar22** [comment]
Hi @Jayjeet1013 Added PR for this issue:- https://github.com/Shubham0850/auraui/pull/29, Please review

**Comment by gaurangkeluskar22** [comment]
Hi @Jayjeet1013, please close this issue as PR for this issue has been merged.

**Comment by Jayjeet1013** [comment]
@gaurangkeluskar22 , thanks for your contribution!
